import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Steve Social",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-slate-100">
          <Navbar />
          <div className="px-8 md:px-10 lg:px-10 xl:px-35 py-6">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
